"""coa is_active and is system changes

Revision ID: 485eec000a56
Revises: 9d6ad2587c24
Create Date: 2026-01-10 19:30:57.438592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485eec000a56'
down_revision: Union[str, Sequence[str], None] = '9d6ad2587c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ledger_groups",
        "is_active",
        server_default=sa.text("true"),
        nullable=False
    )
    op.alter_column(
        "ledger_groups",
        "is_system",
        server_default=sa.text("false"),
        nullable=False
    )

    op.alter_column(
        "ledgers",
        "is_active",
        server_default=sa.text("true"),
        nullable=False
    )
    op.alter_column(
        "ledgers",
        "is_system",
        server_default=sa.text("false"),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ledger_groups", "is_active", server_default=None)
    op.alter_column("ledger_groups", "is_system", server_default=None)
    op.alter_column("ledgers", "is_active", server_default=None)
    op.alter_column("ledgers", "is_system", server_default=None)
    # ### end Alembic commands ###
