"""User model modification

Revision ID: 6a1cceed3b63
Revises: e6e19cf6e5d1
Create Date: 2025-12-30 22:58:09.176862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1cceed3b63'
down_revision: Union[str, Sequence[str], None] = 'e6e19cf6e5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('Users', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password_hash')
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###
