"""chart of accounts

Revision ID: 9d6ad2587c24
Revises: 6a1cceed3b63
Create Date: 2026-01-10 19:10:13.631062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6ad2587c24'
down_revision: Union[str, Sequence[str], None] = '6a1cceed3b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE', 'EQUITY', name='account_type_enum'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(is_system = true AND user_id IS NULL) OR (is_system = false AND user_id IS NOT NULL)', name='ledger_group_system_user_check'),
    sa.ForeignKeyConstraint(['parent_id'], ['ledger_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opening_balance_type', sa.Enum('DEBIT', 'CREDIT', name='balance_type_enum'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(is_system = true AND user_id IS NULL) OR (is_system = false AND user_id IS NOT NULL)', name='ledger_system_user_check'),
    sa.ForeignKeyConstraint(['group_id'], ['ledger_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledgers')
    op.drop_table('ledger_groups')
    # ### end Alembic commands ###
