"""parent and non system group constraints added

Revision ID: c81db2741487
Revises: 485eec000a56
Create Date: 2026-01-10 19:38:04.039553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81db2741487'
down_revision: Union[str, Sequence[str], None] = '485eec000a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE ledger_groups
    ADD CONSTRAINT ledger_group_parent_required_for_user_groups
    CHECK (NOT (is_system = false AND parent_id IS NULL))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE ledger_groups
    DROP CONSTRAINT ledger_group_parent_required_for_user_groups
    """)
    # ### end Alembic commands ###
